# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/ewirch/echoctl:arm64-1_2_1"
labels:
  org.opencontainers.image.title: "echoctl Home Assistant Add-on"
  org.opencontainers.image.description: "Add-on running echoctl on Home Assistant system."
  org.opencontainers.image.source: "https://github.com/ewirch/ha-addons/echoctl"
  org.opencontainers.image.licenses: "Apache License 2.0"
